### ISSUE TITLE
make debugging easier

### ISSUE THREAD

**Issue by madhums** [prismicio/prismic-dom#13]
I am using Prismic-dom with next.js, which means the rendering happens on the server side. Currently Importing `prismic-dom` imports the minified version `dist/prismic-dom.min.js`. If there's any issues (for example, I was debugging #12), it is quite hard to debug as it points to minified version. As a workaround, I tried to point it to `prismic-dom/src`. But then it needs changing of ES6 module system to common js. 

I think this would make debugging a little easier.

What do you people think? Would you be interested if I change the ES6 module syntax to common js and send out a PR? (there's only 4 imports in total, so there's not much)

**Comment by cb-fred** [comment]
I cloned `prismic-dom` locally, changed `main` in `package.json` to point to `dist/prismic-dom.js` and used `yarn link` to use the locally installed `prismic-dom` in my test env, no need for big changes :)

**Comment by arnaudlewis** [comment]
Hi @madhums, I agree with @cb-fred, is simple in dev mode but I prefer keeping minified version for efficiency.
