### ISSUE TITLE
Empty paragraphs breaking RichText.asHtml()

### ISSUE THREAD

**Issue by unremarkablegarden** [prismicio/prismic-dom#16]
Unsure how this affects other people, but for me using Vue.js, trying to render a post that contains a blank-line (empty paragraph) with `PrismicDOM.RichText.asHtml(post.data.content)` breaks the program.

The console says something like: `in render function: "TypeError: Cannot read property 'replace' of null"`

Not all my content editors understand this, so I need to clean up the posts when fetching/storing in my application state before rendering in a template to prevent breaking anything.

```
let i = 0  
post.data.content.forEach((p) => {  
   if (p.text === '') post.data.content.splice(i, 1)  
   i++
})
```

Perhaps `serializeSpan()` is the bad guy here? I'm not sure.
```
function serializeSpan(content) {
  return content ? content.replace(/\n/g, "<br />") : '';
}
```

**Comment by arnaudlewis** [comment]
are you sure you're on the last version of prismic-dom

**Comment by unremarkablegarden** [comment]
Actually it's 2.0.2.

**Comment by unremarkablegarden** [comment]
Oh, yeah. There's the fix. A week ago.
```
FIX: Span contents can be null. 
Frederic Van der essen committed 7 days ago
```
I should have looked, lol

**Comment by moltar** [comment]
Had this issue too. Confirm that this fixed the issue.
