### ISSUE TITLE
import { Date, RichText } from 'prismic-dom' not working

### ISSUE THREAD

**Issue by mtt87** [prismicio/prismic-dom#2]
`import { Date, RichText } from 'prismic-dom'` doesn't work at the moment.

Something like this might work but as you said the problem might be the webpack UMD bundle
```js
export {default as Date} from '@root/date';
export {default as RichText} from '@root/richtext';
```

**Comment by arnaudlewis** [comment]
@mtt87  fixed in 1.1.2
