### ISSUE TITLE
Multiple spans styling ignored

### ISSUE THREAD

**Issue by Kalcode** [prismicio/prismic-dom#21]
In Prismic i have a sentence that has 0 - 18 bold in the sentence and 11-18 italicized. Only the strong tag gets added. If I unbold 11-18, so 0-10 bolded then <em> gets wrapped around 11-18.

Example below:
```json
"spans": [
	{
		"start": 0,
		"end": 18,
		"type": "strong"
	},
	{
		"start": 11,
		"end": 18,
		"type": "em"
	}
]
```

Expected Behavior: Strong and EM gets applied
Actual: First styling gets applied

**Comment by lihbr** [comment]
Actually, this has since been fixed 🎉
