### ISSUE TITLE
HTML characters are not escaped

### ISSUE THREAD

**Issue by Manc** [prismicio/prismic-dom#22]
Hi! Am I missing something or is text not escaped when formatted with `PrismicDOM.RichText.asHtml`?

I'm kind of sure I missed something here. If not – isn't this a huge (huge!) security issue if I don't implement my own asHtml?

Not only would it be a security issue, it would also not allow things like HTML code samples, let's say, in a blog article.

`PrismicDOM.RichText.asHtml` should escape the characters `<`, `>` and `&` in all text content – but obviously not the tags added by `asHtml`.

**Comment by nickw444** [comment]
This is also an issue for me and my team. This is currently blocking us from using Prismic.
