### ISSUE TITLE
Element `preformatted` not implemented

### ISSUE THREAD

**Issue by Manc** [prismicio/prismic-dom#24]
When serialising a _preformatted_ element with `asHtml()` the returned code inside the `<pre></pre>` tags is wrong.

## Expected behaviour:

1. Special HTML characters must be HTML-escaped, e.g. text "<script>" should become `<pre>&lt;script&gt;</pre>`
2. Line breaks must be preserved (that's why it's preformatted).

## Current behaviour:

1. Any text (except line breaks) in a _preformatted_ block is returned as it is, making it impossible to use a _preformatted_ block for HTML code examples and – more importantly – it's a security risk as any code in text would be executed in the browser.
2. Line breaks are replaced with `<br />`.

## Solution

Element _preformatted_ is currently rendered with `serializeStandardTag`, but `pre` tags are not standard.

I've got an implementation ready and a pull request is on its way.

**Comment by Jack-Barry** [comment]
This functionality might work for HTML examples, but breaks others. For example if I want to share some TypeScript code like this:

```ts
class Foo {
  constructor() {}
}

const f = new Foo()

console.log(`'Blah' is a Foo: ${'Blah' instanceof Foo}`)
```

it shows up as this when using `PrismicDOM.RichText.asHtml()`:

```ts
class Foo {
  constructor() {}
}

const f = new Foo()

console.log(`&#39;Blah&#39; is a Foo: ${&#39;Blah&#39; instanceof Foo}`)
```
which as you might understand is a bit frustrating. Is there any way around this? I'm trying to implement PrismJS for syntax highlighting, but this is a big bump in the road to get there.

# EDIT
Was able to get around this with the following snippet

```js
import PrismicDOM from 'prismic-dom'
import Prism from 'prismjs'

export const prismify = data => {
  let richText = PrismicDOM.RichText.asHtml(data)
  // Find all instances of <pre class="language-SOME_LANGUAGE">SOME_CONTENT</pre>
  const toReplace = richText.match(
    /<pre\sclass="language-(?:\w*)">(.*?(?=<\/pre>))<\/pre>/gs
  )

  // Keep track of which match index is being replaced
  let replaceIndex = 0

  data.forEach(docSection => {
    if (docSection.type === 'preformatted') {
      // Use label from Prismic to determine language for PrismJS
      const codeLanguage = docSection.label.replace('language-', '')
      richText = richText.replace(
        toReplace[replaceIndex],
        // Include <pre> and <code> tags as per best practices
        `<pre class="language-${codeLanguage}"><code class="language-${codeLanguage}>` +
          // Throw in the highlighted marked-up code
          Prism.highlight(
            docSection.text,
            Prism.languages[codeLanguage],
            codeLanguage
          ) +
          '</code></pre>'
      )
      // Move to the next replaceIndex for the next preformatted block found
      replaceIndex++
    }
  })
  // Profit
  return richText
}
```
