### ISSUE TITLE
Feature Request: attribute to distinguish link types

### ISSUE THREAD

**Issue by evvvritt** [prismicio/prismic-dom#27]
Hi, just a minor request for some sort of attribute to distinguish the different types of links you can have via Prismic. This way you can style them differently.

Example:
```
<a href="http://myapp.com/about" data-linktype="doc">About</a>
<a href="http://prismic.io/download.pdf" data-linktype="media">Download</a>
...
```

Thanks!

**Comment by lihbr** [comment]
Hey @evvvritt, I'm sorry we failed to give your issue any attention back then.

You can solve that using a custom HTML Serializer ☺️ https://prismic.io/docs/technologies/html-serializer-javascript

Have a great week!
