### ISSUE TITLE
RichText embeds being processed incorrectly

### ISSUE THREAD

**Issue by simplesessions** [prismicio/prismic-dom#28]
I'm using https://github.com/angeloashmore/gatsby-source-prismic and I noticed that when trying to display embedded media in a rich text field, I'm not receiving the correct data back from PrismicDOM.

(More on this here: https://github.com/angeloashmore/gatsby-source-prismic/issues/49)

Digging a little deeper, it seems that when calling `serialize` here: 
https://github.com/prismicio/prismic-dom/blob/master/src/richtext.js?utf8=%E2%9C%93#L86

...it doesn't seem to be passing the type in. Because of this, it seems that the other serialize methods for elements don't get called. In my case, when embedding a YouTube video in a rich text field, I'm returned an object that includes empty `paragraphs` and `spans`, when I should be getting back an object with `oembed` data.

Am I wrong in this assessment?

Thanks!

**Comment by lihbr** [comment]
Hey @simplesessions, I'm sorry we failed to give your issue any attention back then.

I think this has been solved since, feel free to reopen if needed.
