### ISSUE TITLE
.asHtml() removing blocks from rich text field

### ISSUE THREAD

**Issue by adbutterfield** [prismicio/prismic-dom#3]
Hi - I just started experimenting with the new node package, and prismic-dom. I noticed for one of my pages, some headings went missing from rich text fields. I narrowed it down to this line in `dist/prismic-dom.js`:

    return acc.slice(0, acc.length - 2).concat([oList])

I think it should be maybe?

    return acc.slice(0, acc.length - 1).concat([oList])

When I change it to that, it works perfectly.

**Comment by arnaudlewis** [comment]
@adbutterfield Could you give me the piece of content that you put in your structured text that wasn't correctly rendered? thanks.

**Comment by adbutterfield** [comment]
Not sure the best way to do this. But I did some logging in this function: 

    asHtml: function (structuredText, linkResolver, htmlSerializer) {
        ...
    }

Coming in, the structuredText argument is an array like this:

    [{ type: 'heading2',
       text: 'ご利用に際してのご注意（必ずお読みください。）',
       spans: [ { start: 0, end: 23, type: 'label', data: [Object] } ] }
    { type: 'list-item',
       text: '「アクサメディカルアシスタンスサービス」の各サービスは、下記サービス提供会社が提供します。 アクサ生命が提供する保険商品の一部を構成するものではありません。',
       spans: [] }
    { type: 'list-item',
       text: 'サービスの内容は予告なく中止、変更する場合がありますのであらかじめご了承ください。',
       spans: [] }
    { type: 'list-item',
      text: 'サービスのご利用はお客さまの判断のもとに行ってください。 万一、サービス提供を受けた結果、損害が発生してもアクサ生命は責任を負いかねます。',
      spans: [] }]

In that function, it goes through `var elements = structuredText.reduce( ... )`. After it goes through that, the value of elements is:

    [List {
     organized: true,
     value: [ 
       ListItem {
         value: [Object],
         organized: false,
         content: '「アクサメディカルアシスタンスサービス」の各サービスは、下記サービス提供会社が提供します。 アクサ生命が提供する保険商品の一部を構成するものではありません。' },
       ListItem {
         value: [Object],
         organized: false,
         content: 'サービスの内容は予告なく中止、変更する場合がありますのであらかじめご了承ください。' } ] }
    List {
      organized: false,
      value: [ 
        ListItem {
          value: [Object],
          organized: false,
          content: 'サービスのご利用はお客さまの判断のもとに行ってください。 万一、サービス提供を受けた結果、損害が発生してもアクサ生命は責任を負いかねます。' } ] }]

The heading2 just disappears...

**Comment by arnaudlewis** [comment]
@adbutterfield thanks for your report, you can update to 1.2.5 and it'll be ok.

**Comment by adbutterfield** [comment]
Awesome!
