### ISSUE TITLE
Multiple line returns asHtml

### ISSUE THREAD

**Issue by debiasio** [prismicio/prismic-dom#30]
`asHtml` outputs multiple line returns in the writing room as empty paragraph elements.

<img width="175" alt="capture" src="https://user-images.githubusercontent.com/9430761/46208077-d5a16600-c329-11e8-9ae7-88957278d8ab.png">

**Comment by lihbr** [comment]
Hey @jbdebiasio, I'm really sorry we failed to give your issue any attention back then.

I think this is the expected behavior, let us know if anything. Have a great week!
