### ISSUE TITLE
Current version of prismic-dom CDN giving 404 status

### ISSUE THREAD

**Issue by JChristensen97** [prismicio/prismic-dom#31]
I'm using the prismic-dom CDN on a vanilla JS site, and some people are reported that content is not being loaded.
I'm logging the Prismic errors, and prismic-dom CDN is returning with a 404 status. 
There seems to be no correlation between the browsers that are experiencing this issue.
I rolled back the CDN version to 1.2.3, and this fixed the problem.
Any idea why?

Thanks!

**Comment by srenault** [comment]
Hello @JChristensen97,
Having a 404 status make no sense here. Not sure to understand your issue.
What is the CDN you're using?

**Comment by lihbr** [comment]
Closing as stale + we're dropping CDN delivery of this kit I think
