### ISSUE TITLE
90.1 KB minified?

### ISSUE THREAD

**Issue by wiledal** [prismicio/prismic-dom#35]
This script clocks in at a massive 90.1 KB minified.

For context:
- [marked](https://github.com/markedjs/marked), a full blown Markdown parser, is 23.2 KB minified
- React + React DOM is ~106 KB

How is it possible for this to be so positively colossal?

We need to be able to get RichText in a different format like `markdown`, or plain `HTML` **straight from the Prismic API**, or reduce the size of this dependency **tenfold** for it to be usable client-side.

**Comment by hypervillain** [comment]
Hey @wiledal that's definitely a huge issue. I'll try and make a PR today

**Comment by HMilbradt** [comment]
We're running into this as well, and it's really hurting our page speed performance on Google.  We are using Prismic in a Nuxt app, and its size matches the size of the Vue runtime required.  

Are there any plans for fixing or mitigating this?

**Comment by controversial** [comment]
The large dependency in `prismic-dom` seems to be `prismic-richtext`; the verison of `prismic-richtext` required by this repository is 85kb minified. [According to bundlephobia](https://bundlephobia.com/result?p=prismic-richtext@1.0.3), there was an update to `prismic-richtext` over a year ago that cut its size by a factor of nearly 8 (from 85kb to 11). However, `prismic-dom` hasn't been updated to require the new version of `prismic-richtext`. Can anything be done about this, @arnaudlewis ?

**Comment by controversial** [comment]
I opened a pull request that updates `prismic-richtext` (it doesn't seem like the major release of `prismic-richtext` introduced any breaking changes as far as I can tell)

**Comment by simonmaass** [comment]
@arnaudlewis is this abandoned? why is nothing happening?

**Comment by controversial** [comment]
fwiw I'm currently using my fork of this package in my project's `package.json`, while waiting on the PR I submitted

```json
  "dependencies": {
    "prismic-dom": "git+https://git@github.com/controversial/prismic-dom.git"
  }
```
https://github.com/controversial/luk.ke/blob/0fbce9e2baa5e28e74c005681c4c43c167bbde24/package.json#L26

**Comment by simonmaass** [comment]
@hypervillain can you release this in new version?

**Comment by simonmaass** [comment]
@hypervillain ping!

**Comment by simonmaass** [comment]
@arnaudlewis ping

**Comment by controversial** [comment]
Looks like @arnaudlewis made a new release a couple hours ago - thanks   ❤️

**Comment by controversial** [comment]
Might have spoken too soon - it looks like there was a 2.1.2 release made that had a smaller bundle size but it jumped back up with a 2.1.3 release that's not pushed to this git repository yet. Do you know what's going on with that @arnaudlewis @hypervillain ?

<img width="542" alt="Screen Shot 2020-04-14 at 2 11 13 PM" src="https://user-images.githubusercontent.com/10377391/79258913-da6d3280-7e59-11ea-9789-ccc4760f94b5.png">

**Comment by hypervillain** [comment]
Unfortunately, we has some issue with the previous deployment but will be
working on it tomorrow.
Sorry for the inconvenience, it's been a long way

**Comment by arnaudlewis** [comment]
Hey guys, sorry for the inconvenience, we had some browser issues forcing us to rollback our build but now the version `2.2.3` is stable and is below 20kB ;)
Thank you for your patience.
