### ISSUE TITLE
RichText.asHtml with link undefined

### ISSUE THREAD

**Issue by DCKT** [prismicio/prismic-dom#4]
Hello,

I'm trying this module with the [prismic-javascript](https://github.com/prismicio/prismic-javascript) module and I have a strange behavior on a paragraph with a link.

I've put a linkResolver but it seems not to be called (`console.log` are not triggerd) : 
```javascript
DOM.RichText.asHtml(
  data.page.body.value[1].value.value[0].desc.value,
    (doc, ctx) => {
       console.log(doc)
       console.log(ctx)
       if (doc.type === 'test') return `/page/${doc.uid}`
       return '/'
    }
)
```

Here is the span in the paragraph : 
```javascript
{ start: 30,
  end: 37,
  type: 'hyperlink',
  data: { type: 'Link.web', value: { url: 'http://test.fr' } } }
```

And here is the result : 
```html
<p class="">Précurseur de la <strong class="">livraison</strong> du <a href="undefined">dernier</a> kilomètre</p>
```

Am I doing something wrong ?

Thanks for your help.

**Comment by arnaudlewis** [comment]
Thanks for your feedback @DCKT, actually, it was an issue due to a breaking change in the API during the beta test.
In the last version a just based the url generation on the new Link Helper which helps getting a url from any kind of link.
You should update to 1.2.3

**Comment by DCKT** [comment]
Hello @arnaudlewis 
Do you have an example, I've upgraded the package and I keep getting the same behavior (external URL with no link resolver)

**Comment by arnaudlewis** [comment]
@DCKT https://github.com/arnaudlewis/prismic-apiv2/blob/master/views/index.pug#L61
this is how we handle document link url with prismic dom. it's internally used for structured text here : https://github.com/prismicio/prismic-dom/blob/master/src/utils/spans.ts#L65

**Comment by DCKT** [comment]
Hmm still the same : 
<img width="1099" alt="capture d ecran 2017-06-02 a 17 18 39" src="https://cloud.githubusercontent.com/assets/1548421/26732572/55d0dd7c-47b8-11e7-8b20-5c212e8c313e.png">

My package.json is up to date : 
```json
"prismic-dom": "^1.2.3",
"prismic-javascript": "^1.1.1",
```

**Comment by DCKT** [comment]
By the way, I've found [this throw an error](https://github.com/prismicio/prismic-dom/blob/v1.2.3/src/link.ts#L3) because now the api return an object with `type` and not `link_type`

**Comment by arnaudlewis** [comment]
You're not on the API v2 according to the screenshot and prismic-javascript/prismic-dom are meant to be used with the api v2. prismic-javascript should always work perfectly with v1 because it doesn't change the api response at all but prismic-dom is based on v2 response.
You can use the javascript-kit for v1 or make you own implementation for RichText rendering.
If you can, the best would be to migrate to the api v2.

**Comment by arnaudlewis** [comment]
@DCKT It seems that you're on the api v1 according to your screenshot. Prismic-dom and prismic-javascript are meant to be used with api v2 so I suggest you to migrate to api v2 or simply use the javascript-kit for api v1 : https://github.com/prismicio/javascript-kit

**Comment by DCKT** [comment]
Oh sorry i didn't pay attention about my api version, do you know where can I do the migration ?

**Comment by arnaudlewis** [comment]
New repos have access to it by adding "/v2" at the end of your endpoint. If it returns a 404, just give me your repository name and I'll activate the feature for you.

**Comment by DCKT** [comment]
Ok, my repo has access to the v2 API.
When I try to call a page by UID, the request keep pending with no response.

```javascript
return Prismic.api('https://testcolisweb.cdn.prismic.io/api/v2').then(api => {
  return api
    .getByUID('page', 'home')
    .then(t => {
       // never called
       console.log(t)
    })
})
```

Am I doing something wrong ? Thanks for your help !

**Comment by arnaudlewis** [comment]
I can move you to the api v2 @DCKT but when it's done, you must republish a document first to make the api v2 up and running for technical reason since it's still in beta.
