### ISSUE TITLE
Inline image from wysiwyg renders as link

### ISSUE THREAD

**Issue by rafaelderolez** [prismicio/prismic-dom#5]
An image from the wysiwyg is rendered in the HTML wrapped by an `<a>` tag. When clicking the Image it automatically starts downloading.

<img width="1175" alt="2017-06-27164131" src="https://user-images.githubusercontent.com/6158959/27593878-a940c040-5b58-11e7-9acf-eb936b1fdbf3.png">

**Comment by arnaudlewis** [comment]
fixed in 1.2.7
