### ISSUE TITLE
Inline image from wysiwyg is logged to console

### ISSUE THREAD

**Issue by rafaelderolez** [prismicio/prismic-dom#6]
<img width="1265" alt="2017-06-27165551" src="https://user-images.githubusercontent.com/6158959/27594216-83c1da38-5b59-11e7-9f13-c03c11075a9f.png">

https://github.com/prismicio/prismic-dom/blob/cace4af161f06062552e7a8b0d5ac1079d8ed7ef/src/elements.ts#L194

**Comment by arnaudlewis** [comment]
fixed in 1.2.7
